### ISSUE TITLE
Screen Border Limitations Needed

### ISSUE THREAD

**Issue by jpyper** [ztiromoritz/pico-8-shooter#5]
This is a fun little simple game. One caveat I noticed just on the first time playing was that you can move your ship completely off the screen in either the X or Y axis, which is kind of boggling. If you move your ship off the screen either to the top or the bottom, your ship still takes damage from the enemies and you can't see them or your ship.

Just thought I'd point that out. Keep up the great work, and I look forward to seeing where this game goes.

**Comment by ztiromoritz** [comment]
Thanks, good point.

**Comment by ztiromoritz** [comment]
Won't fix this in the gif and cardridge but added a next steps/known issues note section to the page.
